### ISSUE TITLE
[Announcements] Code release

### ISSUE THREAD

**Issue by Skydes** [cvg/pixel-perfect-sfm#1]
Hit the `subscribe` button on the right of this issue if you wish to be notified of the code release. Please do not reply to this issue to not spam other subscribers. Please do not contact us to ask for early-access to the code.

**Comment by hiyyg** [comment]
subscribe

**Comment by DeriZSY** [comment]
Looking forward to the code of PixLoc!!!

**Comment by EnriqueSolarte** [comment]
subscribee

**Comment by hiyyg** [comment]
subscribe

**Comment by jiushihaishi** [comment]
subscribe

**Comment by HollisJoe** [comment]
Subscribe

**Comment by huijieZH** [comment]
Subscribe

**Comment by xuezhou08** [comment]
subscribe

**Comment by Skydes** [comment]
Hi all, we have now finally released the code! This has taken far more time than we expected, sincere apologies for the delay. We have worked hard to turn our research code into a nice Python package with significantly improved usability, accuracy, and scalability. It integrates well with COLMAP and hloc and is highly configurable to fit many use case. I am very proud of this release and excited to see what the community will do of it. Please give it a try and let us know if you run into any trouble or need advice!
