### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by WPC-WHU** [cvg/pixel-perfect-sfm#103]
File "/media/wpc/newssds/ImageMatching/pixel-perfect-sfm/pixsfm/__init__.py", line 17, in <module>
    from ._pixsfm import *  # noqa F403
ImportError: /media/wpc/newssds/ImageMatching/pixel-perfect-sfm/pixsfm/_pixsfm.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN5ceres7Problem25SetParameterBlockConstantEPd

**Comment by jytime** [comment]
Hi Paul, I also met a similar error as below

<img width="1633" alt="Screenshot 2023-05-26 at 23 44 45" src="https://github.com/cvg/pixel-perfect-sfm/assets/37647961/ac40b4c8-fc8f-4775-a304-fbed1c33d44a">

My environment can successfully import pyceres and related packages, with ceres-solver of version 2.1. Did I miss anything here?

**Comment by WPC-WHU** [comment]
The cause of the error may be that the original version of Ceres was used when installing ColMap and the updated Ceres was used when installing Pixsfm. I solved this problem by re-install colmap using ceres2.1. However，when I run the demo, another error has occurred 
![图片](https://github.com/cvg/pixel-perfect-sfm/assets/32131223/67c02d65-b79c-421e-a17b-dc58e7948d96)
Debug information:
![图片](https://github.com/cvg/pixel-perfect-sfm/assets/32131223/fb279cbb-4ba8-4388-be7f-abf80fcd6f9a)

**Comment by Phil26AT** [comment]
Great that you could resolve it. We probably should check for version mismatches in cmake, I'll put in on my ToDo. 

As for your error: Are you using pycolmap from pypi? I suggest reinstalling pycolmap from source too, this is likely the cause of the error.

**Comment by WPC-WHU** [comment]
Thanks for your help，I reinstalling pycolmap from source and it is working now.

**Comment by jytime** [comment]
Thank you guys @WPC-WHU @Phil26AT . I solved it by reinstalling all the packages from source and now it works. Another thing worth mentioning is that if the torchvision is installed by conda, it will automatically install libtiff to conda env and would hide the original libtiff link. A bit close to this issue https://github.com/colmap/pycolmap/issues/105.

**Comment by Phil26AT** [comment]
Hi @jytime, great that you also solved the issue!

Yes libtiff is known to conflict with conda. A simpler solution would be to install colmap via conda and then install pycolmap, pyceres and pixsfm. However, we have not tested this yet.
