### ISSUE TITLE
TooMuch Time on Reconstruction block in Demo

### ISSUE THREAD

**Issue by bdxuyidong** [cvg/pixel-perfect-sfm#104]
Thanks for your work. I m running the Demo.ipynb with the sacre_coeur datasets. It is already 40mins and it still dont finish the reconstruction code block. I dont know if there is anything wrong with the reconstruction code because the dataset is very small.I m using cuda11.6, torch1.13. 
![Screenshot from 2023-05-27 22-28-41](https://github.com/cvg/pixel-perfect-sfm/assets/82100273/2d49800c-d8fe-42be-82d2-314b468a4f5b)

**Comment by bdxuyidong** [comment]
![Screenshot from 2023-05-27 22-28-41](https://github.com/cvg/pixel-perfect-sfm/assets/82100273/867803db-1c2f-4acb-945d-8ae010ffd315)

**Comment by ericufatass** [comment]
Hey, do u find the way to speed it up?
