### ISSUE TITLE
LightGlue

### ISSUE THREAD

**Issue by ThomasParistech** [cvg/pixel-perfect-sfm#108]
I've noticed that you released LightGlue a few days ago. Sounds great !
Do you plan on making it available in Hloc and pixsfm ?

Many thanks :)

**Comment by Phil26AT** [comment]
Hey @ThomasParistech. Yes, we plan to make it available in hloc in the next days.

**Comment by Phil26AT** [comment]
cvg/Hierarchical-Localization#285
