### ISSUE TITLE
Bug: Need to remove ANTIALIAS

### ISSUE THREAD

**Issue by catid** [cvg/pixel-perfect-sfm#119]
In extractor.py:

```
    filters = {
        n: getattr(PIL.Image, n)
        for n in ["BILINEAR", "BICUBIC", "ANTIALIAS", "LANCZOS"]
    }
```

The "ANTIALIAS" option has been deprecated for a while and is now removed and is causing build problems.

**Comment by Skydes** [comment]
Thanks, could you please submit a PR that removes it?
