### ISSUE TITLE
About feature-reference bundle adjustment.

### ISSUE THREAD

**Issue by leo-frank** [cvg/pixel-perfect-sfm#123]
I am running pixSFM. From code, I know that pixSFM consists of 3 steps: KA, colmap and BA.
I print reconstruction.summary() before and after BA in function refine_hloc.py/PixSfm/run 
which corresponding to "LINE 1" and "LINE 2" respectively in the following screenshot 

![image](https://github.com/cvg/pixel-perfect-sfm/assets/47302141/ac0b532a-4b98-4db7-b98e-66a649de4d94)

I found that the two pieces of output statistics are same! 

![image](https://github.com/cvg/pixel-perfect-sfm/assets/47302141/de018e44-bc7c-412e-91c8-1b61618c1c67)

So is there any statistic that reflects BA?

**Comment by Phil26AT** [comment]
Hey, indeed the parameters are not updated in F-BA - the reason for that is that pixsfm does not update point tracks (so track length remains the same), and the reprojection error has no meaning anymore after F-BA (in contrast to geometric BA, which minimizes the reprojection error).
Instead, you should look at the cost changes in BA. Your cost decreases from 0.02078 to 0.0204, which is reasonable and some improvements should be visible in the reconstruction.

**Comment by leo-frank** [comment]
Thanks! Close it

**Comment by leo-frank** [comment]
THX! Close it！
