### ISSUE TITLE
ModuleNotFoundError: No module named 'pixsfm.refine_hloc'

### ISSUE THREAD

**Issue by Legend94rz** [cvg/pixel-perfect-sfm#127]
I have created a clean environment using conda: `conda create -n python==3.10`.
Then I install pixsfm and pytorch (and other deps): `conda install pytorch torchvision torchaudio pytorch-cuda pixsfm -c pytorch -c nvidia -c conda-forge`.

Now,  if I write `from pixsfm.refine_hloc import PixSfM`
will give error:
`ModuleNotFoundError: No module named 'pixsfm.refine_hloc'`.

I tried to install `hloc` then: `conda install hloc -c conda-forge`, but it doesn't work.

Could you please give some help?

**Comment by Legend94rz** [comment]
In fact, import other sub-module of `pixsfm` will give similar error, e.g.:
```
Python 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pixsfm.refine_hloc import PixSfM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pixsfm.refine_hloc'
>>> import pixsfm
>>> pixsfm
<module 'pixsfm' (<_frozen_importlib_external._NamespaceLoader object at 0x7f7fe69c7130>)>
>>> from pixsfm.util.visualize import init_image, plot_points2D
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pixsfm.util'
>>> from pixsfm import ostream_redirect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ostream_redirect' from 'pixsfm' (unknown location)
>>> dir(pixsfm)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

**Comment by gregogalante** [comment]
@Legend94rz I'm getting the same problem. Did you find a solution?

**Comment by Legend94rz** [comment]
> @Legend94rz I'm getting the same problem. Did you find a solution?

not yet

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/pixsfm-feedstock/pull/7 - I'm working on it

**Comment by Tobias-Fischer** [comment]
Should be all good now with the latest build.

**Comment by Legend94rz** [comment]
@Tobias-Fischer Hi, really thanks for your help!
I have re-create a new env and reinstall pixsfm via conda.
it seems like the problem still exists...
the version pixsfm I installed is:
`pixsfm                          1.0.0  py310h64457ac_2               conda-forge`
is it correct?

**Comment by Tobias-Fischer** [comment]
No, you want build number 3 instead of 2 as you currently have. Can you try creating a new environment with just pixsfm in there?

**Comment by Legend94rz** [comment]
I'm using this cmd:
`conda create -n pixsfm pixsfm -c pytorch -c nvidia  -c conda-forge`

here are some versions of installing packages:
```
colmap-3.8                 |  gpuh7f4bfd4_109        68.8 MB  conda-forge
cudatoolkit-11.8.0         |      h4ba93d1_12       682.8 MB  conda-forge
pixsfm-1.0.0               |  gpuhe00762b_103         2.4 MB  conda-forge
pycolmap-0.4.0             |cuda112py311h35f17e9_5        34.0 MB  conda-forge
pyparsing-3.1.1            |     pyhd8ed1ab_0          87 KB  conda-forge
python-3.11.6              |hab00c5b_0_cpython        29.3 MB  conda-forge
pytorch-2.0.0              |cpu_generic_py311h495eaba_4        69.3 MB  conda-forge
```
the installing pytorch may not support CUDA..
Maybe I need install pixsfm first and then re-install pytorch from official?

**Comment by Tobias-Fischer** [comment]
Hiya - try `mamba create -n pixsfm pixsfm pytorch-gpu -c conda-forge` which works for me :)
(general comment: try and not mix different channels, I use conda-forge for everything)

**Comment by Legend94rz** [comment]
> Hiya - try `mamba create -n pixsfm pixsfm pytorch-gpu -c conda-forge` which works for me :) (general comment: try and not mix different channels, I use conda-forge for everything)

I tried your cmd and now pixsfm works fine. Thank you!

**Comment by liyupeng-ing** [comment]
`from pixsfm.refine_hloc import PixSfM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lyp/miniforge3/envs/pixsfm-test/lib/python3.11/site-packages/pixsfm/__init__.py", line 25, in <module>
    pyceres.glog.minloglevel = 4
    ^^^^^^^^^^^^
AttributeError: module 'pyceres' has no attribute 'glog'`
hi! i get some error, can you give me some help? Thank you!

`pixsfm                                       1.0.0  gpuhf31afc4_105            conda-forge/linux-64        3MB`

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/pixsfm-feedstock/issues/15
