### ISSUE TITLE
Inference time on sparse frames

### ISSUE THREAD

**Issue by jytime** [cvg/pixel-perfect-sfm#134]
Hi Philipp and Paul,

I was hoping to report the speed of PixelSfM in our paper. In our cluster with A100 GPU, when given 25 frames (usually 1200x800), we observed that PixelSfM typically takes between 180 to 210 seconds to complete a reconstruction. To ensure comparing to PixelSfM fairly (and avoiding any inadvertent mistakes), may I ask if these results look reasonable to you? 

Best,
Jianyuan

**Comment by Phil26AT** [comment]
Hi Jianyuan, yes this looks reasonable.

**Comment by jytime** [comment]
Thank you!
