### ISSUE TITLE
Scale of Cauchy loss

### ISSUE THREAD

**Issue by melhashash** [cvg/pixel-perfect-sfm#15]
Hello,

What is the rationale behind setting the scale of Cauchy loss to 0.25, have you tested different values?

**Comment by Skydes** [comment]
Hi,
Sorry for the late reply. As far as I recall we tested a few values and found this one to work well for S2DNet features. We did not tune this extensively and the value might not be optimal for other dense features.

**Comment by melhashash** [comment]
@Skydes Thanks for the reply!
