### ISSUE TITLE
Error building pixsfm

### ISSUE THREAD

**Issue by joseTWD** [cvg/pixel-perfect-sfm#150]
Hi everyone,

I'm trying to build a container from Dockerfile with multiple packages, pixsfm included, but at the time it is being built, I have the following error (according to GPT it is due to lack of resources, but no matter what I do it keeps failling):

![Captura de pantalla 2024-10-25 094300](https://github.com/user-attachments/assets/f525297b-5b94-4790-9446-05454893546e)

![Captura de pantalla 2024-10-25 094529](https://github.com/user-attachments/assets/dc5d5df6-6658-49bb-8b26-4e95de534a2a)

Please can someone provide any tip? :)

**Comment by joseTWD** [comment]
It was finally solved extending swap memory :)

**Comment by mattiasmar** [comment]
@joseTWD Could you please share your Dockerfile? I gave it a quick try with latest colmap commit and got tons of errors.

**Comment by joseTWD** [comment]
Hi @mattiasmar ! Sure, here is the Dockerfile.
[Dockerfile.zip](https://github.com/user-attachments/files/17990695/Dockerfile.zip)

In my case, I had to create a .wslconfig file and place it in the C:/Users/User directory to make effective the extension of memory, as I said in the previous comment. Hope it works for you! :)

**Comment by mattiasmar** [comment]
Thanks! But where are the pixsfm sources in that docker?

**Comment by joseTWD** [comment]
Hey sorry! I forgot pixsfm and others are built in a .toml



[pyproject.zip](https://github.com/user-attachments/files/17991555/pyproject.zip)

**Comment by mattiasmar** [comment]
So you build your dockerfile and then do `python -m build` in an folder that's empty besides this toml file?
