### ISSUE TITLE
Tanks and Temples eval?

### ISSUE THREAD

**Issue by pwais** [cvg/pixel-perfect-sfm#16]
Hi, Thanks for making this code available, and especially for the pycolmap improvements-- those have been needed for a very long time and the effort will have a big impact.

Have you evaluated this method on Tanks and Temples (or considered doing so) ?  The object-centric scenes are a perhaps bit different-- there is perhaps more range of depth and background keypoints have less support (fewer images).  If not, do you see more relevance with ETH3D?

**Comment by Skydes** [comment]
Hi, thanks for the suggestion. I don't have first-hand experience with T&T but it indeed could be suitable to evaluate both triangulation and pose estimation in the same way as we do on ETH3D. Besides sparse triangulation, we could also evaluate dense MVS (e.g. with COLMAP) with camera parameters refined using PixSfM. This is what [Woodford et al.](https://arxiv.org/pdf/2008.11762.pdf) report and it seems to work quite well.

This evaluation should be fairly easy to add here, e.g. in `pixsfm/eval/tt/`. I don't really have time to implement it but you are welcome to contribute it!

On the differences between ETH3D and T&T: it's hard to say as both cover indoor and outdoor with long- and short-range structure.

**Comment by pwais** [comment]
Thanks for the pointer @Skydes  !  I had not picked thru the related work in your paper yet.  

Looking a bit more, it seems ETH3D and T&T use the same laser scanner (!) although ETH3D appears to have much better (and more carefully established) camera registration.  So it sounds like one dataset may not obviously uncover different issues than the other.

A follow-up though: I'm curious about how distance could throw off keypoint refinement.  For example, suppose half of the scene's keypoints are on an object within 1 meter of the camera, while the other half are >10m away on the background.  That could mess with the optimization objective and produce poor bundle adjustment.  In the paper, it seems you peeps grapple with that a bit, and you note that: 

```
For each track, we freeze the location of the keypoint \hat{u} with highest connectivity, as in [24], and constrain the
location p_u of each keypoint w.r.t. to its initial detection ||p_u - p_u^0 || \leq K
```

Dumb questions:
 * How did you choose `K`?  Is it different for every benchmark?  Can I twiddle this parameter in the code (e.g. `refine_keypoints?`)
 *  Did you find this constraint made a big difference?  Was it more useful versus the feature correspondence weights / checks ?

**Comment by Skydes** [comment]
Looking closer at T&T, there is a clear difference with ETH3D: ETH3D provides GT camera poses & parameters and only evaluate the sparse/dense reconstruction via triangulation/MVS. T&T does not release the GT camera poses & parameters so it evaluates the full SfM pipeline, including pose estimation. I think that PixSfM could help a lot there.

> A follow-up though: I'm curious about how distance could throw off keypoint refinement. For example, suppose half of the scene's keypoints are on an object within 1 meter of the camera, while the other half are >10m away on the background. That could mess with the optimization objective and produce poor bundle adjustment. In the paper, it seems you peeps grapple with that a bit, and you note that:

The constraint on the point movement is applied in the keypoint adjustment, so large distance differences don't matter at that stage. They do indeed matter in the bundle adjustment, but this also applies to geometric BA and we can't do much about it.

In the code `K` is set in the config entry `KA.optimizer.bound`:
https://github.com/cvg/pixel-perfect-sfm/blob/8701bd208205f6041875c51ccefebdf571113b1f/pixsfm/keypoint_adjustment/main.py#L78
We don't tune it per scene but it might need to be increased for keypoint detectors that have a higher noise. If sparse feature patch extraction is enabled (by default), `K` should be lower or equal to half the patch size `dense_features.patch_size`.

About the impact: this constraint prevents drift for tracks that are poorly constrained by the featuremetric cost, such as textureless areas. For most tracks this does not apply so it has a small impact.

**Comment by pwais** [comment]
> Looking closer at T&T, there is a clear difference with ETH3D: ETH3D provides GT camera poses & parameters and only evaluate the sparse/dense reconstruction via triangulation/MVS. T&T does not release the GT camera poses & parameters so it evaluates the full SfM pipeline, including pose estimation. I think that PixSfM could help a lot there.

Right, T&T lacks registered poses.  I wanted to say the laser scans might be better (they seem to have spent longer doing the scans), but they appear to use the same laser scanner as ETH3D.  There could be an interesting experiment though: run PixSfM on T&T and compare with PixSfM/ETH3D using a reconstruction-based metric.  E.g. align the SfM point cloud to the fused laser scan in the same way, then measure chamfer distance or something.  Since the laser scans should be similar quality, T&T becomes a large test set.  


> We don't tune it per scene but it might need to be increased for keypoint detectors that have a higher noise.

Ah! Thanks for the code citation and the extra info.  That make sense that it should be proportional to patch size.  Thank you!

**Comment by silver-obelisk** [comment]
> Looking closer at T&T, there is a clear difference with ETH3D: ETH3D provides GT camera poses & parameters and only evaluate the sparse/dense reconstruction via triangulation/MVS. T&T does not release the GT camera poses & parameters so it evaluates the full SfM pipeline, including pose estimation. I think that PixSfM could help a lot there.
> 
> > A follow-up though: I'm curious about how distance could throw off keypoint refinement. For example, suppose half of the scene's keypoints are on an object within 1 meter of the camera, while the other half are >10m away on the background. That could mess with the optimization objective and produce poor bundle adjustment. In the paper, it seems you peeps grapple with that a bit, and you note that:
> 
> The constraint on the point movement is applied in the keypoint adjustment, so large distance differences don't matter at that stage. They do indeed matter in the bundle adjustment, but this also applies to geometric BA and we can't do much about it.
> 
> In the code `K` is set in the config entry `KA.optimizer.bound`:
> 
> https://github.com/cvg/pixel-perfect-sfm/blob/8701bd208205f6041875c51ccefebdf571113b1f/pixsfm/keypoint_adjustment/main.py#L78
> 
> 
> We don't tune it per scene but it might need to be increased for keypoint detectors that have a higher noise. If sparse feature patch extraction is enabled (by default), `K` should be lower or equal to half the patch size `dense_features.patch_size`.
> About the impact: this constraint prevents drift for tracks that are poorly constrained by the featuremetric cost, such as textureless areas. For most tracks this does not apply so it has a small impact.

Hi,I  try to use pixsfm in TT,but actually I found it donot work well compared with ETH3d. In eth3d pixsfm can decrease reprojection about 0.4  but only 0.1 in TT and number of 3d points also decreased. I wonder is it didnot work on TT or just need a  good  config?
