### ISSUE TITLE
Costmap containers crash if some images have no observations

### ISSUE THREAD

**Issue by Skydes** [cvg/pixel-perfect-sfm#21]
Error described in https://github.com/cvg/pixel-perfect-sfm/issues/17 with data from https://github.com/ThomasParistech/test_pixsfm. Following error message with all debug enabled:
```
[2022/01/28 08:47:50 pixsfm INFO] Extracting references and costmaps.
Segmentation fault (core dumped)
```
According to @ThomasParistech and faulthandler the crash occurs in:
https://github.com/cvg/pixel-perfect-sfm/blob/8701bd208205f6041875c51ccefebdf571113b1f/pixsfm/bundle_adjustment/main.py#L263-L267

**Comment by Phil26AT** [comment]
Fixed on branch [`fix-costmaps`](https://github.com/cvg/pixel-perfect-sfm/tree/fix-costmaps).
