### ISSUE TITLE
Core dump during feature-metric keypoint adjustment

### ISSUE THREAD

**Issue by Xiaobin-Jiang** [cvg/pixel-perfect-sfm#26]
I'm trying to refine keypoint from database，and I get core dump during Start feature-metric keypoint adjustment. 

The database is built on superpoint and superglue. When the descriptor does not exist in the database, the program will core dump.  If the score is empty, this situation will be handle in the [Graph::RegisterMatches](https://github.com/cvg/pixel-perfect-sfm/blob/dcd8a5fc5a9f8413d40c1808125aa066452ef3cc/pixsfm/base/src/graph.cc#L66-L80), what is the cause of this problem？

```C
void Graph::RegisterMatches(std::string imname1, std::string imname2,
                            size_t* matches,       // Nx2
                            double* similarities,  // Nx1
                            size_t n_matches) {
  for (size_t match_idx = 0; match_idx < n_matches; ++match_idx) {
    colmap::point2D_t feature_idx1 = matches[2 * match_idx];
    colmap::point2D_t feature_idx2 = matches[2 * match_idx + 1];
    **double similarity = similarities ? similarities[match_idx] : 1.0;**

    FeatureNode* node1 = FindOrCreateNode(imname1, feature_idx1);
    FeatureNode* node2 = FindOrCreateNode(imname2, feature_idx2);

    AddEdge(node1, node2, similarity);
  }
}
```
When I import the descriptor of superpoint and read it accoording to float32, it still core dump in feature-metric keypoint adjustment. But I use the default uint8 to read the descriptor and the program works fine. I don`t think this is normal, the superpoint descriptor should not be of uint8.   What is the cause of this problem？

my code
```Python
conf = {
        "dense_features": {"use_cache": True,
        "max_edge": 1024},
}
refiner = PixSfM(conf=conf)
keypoints, _, _ = refiner.refine_keypoints_from_db(
        refined_database,
        database,
        image_dir,
        )
```

Thanks in advance!

my environment：
Ubuntu 16.04
Python 3.8

**Comment by Phil26AT** [comment]
HI @Xiaobin-Jiang,

Thank you for reporting this problem. Indeed there was a bug in handling databases without descriptors, we pushed a fix to the branch [`fix-db-no-descriptors`](https://github.com/cvg/pixel-perfect-sfm/tree/fix-db-no-descriptors). Please let us know if this resolves your issue.

COLMAP databases require descriptors stored as uint8 ([see here](https://colmap.github.io/database.html#keypoints-and-descriptors)), and other data types might thus fail with COLMAP. If you would like to work with custom descriptors, we suggest using [hloc](https://github.com/cvg/Hierarchical-Localization), refine the keypoints in the hloc feature file and then import the refined keypoints to the database.

**Comment by Xiaobin-Jiang** [comment]
@Phil26AT 

Thank you for your reply.  I used the fixed branch [fix-db-no-descriptors](https://github.com/cvg/pixel-perfect-sfm/tree/fix-db-no-descriptors) for testing. The program seems to work fine, but compared to the database with descriptors, the running time is much slower, and the memory usage is much larger. Both time and memory seem to be four times as long as a database with descriptors.

database without descriptors:
![image](https://user-images.githubusercontent.com/37786958/154032118-969a0bfb-e6e2-472e-b89e-0b95da9ae31a.png)
and memory used:
![image](https://user-images.githubusercontent.com/37786958/154032250-442b76e2-8877-4795-b59e-0af80f2adce1.png)

database with descriptors:
![image](https://user-images.githubusercontent.com/37786958/154032312-413facd6-818f-4162-99aa-f33c7042ef1e.png)
and memory used:
![image](https://user-images.githubusercontent.com/37786958/154032383-5700de7e-7525-4d1f-9554-5cd247946ff1.png)

> COLMAP databases require descriptors stored as uint8 ([see here](https://colmap.github.io/database.html#keypoints-and-descriptors)), and other data types might thus fail with COLMAP. If you would like to work with custom descriptors, we suggest using [hloc](https://github.com/cvg/Hierarchical-Localization), refine the keypoints in the hloc feature file and then import the refined keypoints to the database.

Descriptors are only used when computing scores [read_matches_from_db](https://github.com/cvg/pixel-perfect-sfm/blob/main/pixsfm/util/colmap.py#L36-L38). It is obtained directly from the database through sql query and has nothing to do with the colmap code.  After querying the data from sql, it just converts the descriptors into different types. Different types do not affect the calculation of the score.  I don't see the descriptor information being used in the following program.
```python
for image_id, r, c, data in db.execute("SELECT * FROM descriptors"):
    d = blob_to_array(data, np.uint8, (-1, c))
    desc[image_id] = d / np.linalg.norm(d, axis=1, keepdims=True)
```

I wonder how time and memory can change so much without descriptors, why dose reading the descritptor according to float32 cause  _feature-metric keypoint adjustment_ to crash.

**Comment by Xiaobin-Jiang** [comment]
@Phil26AT 

I used the merged branch [fix-db-no-descriptors](https://github.com/cvg/pixel-perfect-sfm/tree/fix-db-no-descriptors) for testing, it works fine. So, do I still need to share data with you?

> In theory, you should be able to work with float32 descriptors without any issues during KA. A possible reason why it fails might be an incorrect reading of the descriptors. Have you checked the resulting scores obtained from these descriptors? They should be in the range [0, 1].

I have checked that the scores of the descriptors are all in the range [0, 1]. The shape of the descriptors read from the database is correct.  I used merged branch  [fix-db-no-descriptors](https://github.com/cvg/pixel-perfect-sfm/tree/fix-db-no-descriptors),  descriptors parsed with float32 work fine. Which was much slower than the without descriptors. 
Without descriptor KA time: 32min
With descriptor KA time: 0.81min

Please let me know is this correct?
Thanks.
