### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by otri** [cvg/pixel-perfect-sfm#3]
With all the amazing light field papers coming out in Jan 2022, it would be amazing to pair this work with them.  Is the COLMAP plugin code coming soon?

**Comment by yuxiang-wen** [comment]
收到，谢谢

**Comment by Skydes** [comment]
Thank you for your interest. The code is now released, see https://github.com/cvg/pixel-perfect-sfm/issues/1#issuecomment-1018891795.

**Comment by otri** [comment]
Thank you!! Excited to work with it!
 Cheers!
