### ISSUE TITLE
Very sparse images matched incorrectly

### ISSUE THREAD

**Issue by cduguet** [cvg/pixel-perfect-sfm#30]
I have been trying to locate the camera positions for [this very challenging dataset](https://drive.google.com/drive/folders/1DLJhoSvDFBg6relMvaxzadn_gVzVJmP5?usp=sharing). It is a 360 from a sofa with very little texture and views are very sparse. I can only get 10 cameras poses, whether with COLMAP or pixsfm. The successful ones are frontal, while the laterals and rear ones fail.

In other software(COLMAP), I've been trying to constraint the matching only to the images described by a manually made `image_pairs.txt` in order to enforce that the images match to the ones I want. I would like to try the same with pixsfm, but even though I see `refiner.reconstruction` accepts a `list_of_image_pairs`, the matching seems to happen before. 

I assume I need to create image pairs with `pairs_from_*` but I can't seem to find one that accepts an input text. 

I could also find a way to manually create guesstimated priors to correctly initialize optimization, but I don't know of an easy way to do this. 

I have other datasets of very shiny objects with which I get into similar problems. What would you recommend doing? 

Thank you very much in advance!

**Comment by Skydes** [comment]
Sorry for the late reply. This is indeed a fairly challenging set of images for COLMAP. Does providing the manual list of pairs improve the reconstruction of COLMAP? In this scenario I do not think that pixsfm will do better than COLMAP. If you nevertheless want to give it a try, you can see in the [`demo.ipynb`](https://github.com/cvg/pixel-perfect-sfm/blob/main/demo.ipynb) that we pass a path to a list of pairs to `PixSfM.reconstruction` - you can simply swap it with your own list.

**Comment by cduguet** [comment]
Thank you very much! You're indeed right, that there is little to do with that dataset.
