### ISSUE TITLE
Question of Eq.(4) in paper

### ISSUE THREAD

**Issue by Vincentqyw** [cvg/pixel-perfect-sfm#31]
Thank you for open source this great project. 
Recently I read your`pixel-perfect-sfm` paper. I have one question in Eq.(4)  which can be described as follows: 

![image](https://user-images.githubusercontent.com/18531182/156211575-f4ad38c2-265b-4fad-a939-894c9af6d4c0.png)

I think the key idea of  `FKA` is to minimize error between matched keypoints from different images in feature-metric domain. I don't know if I am right?

**Comment by Phil26AT** [comment]
Indeed you are right. Here, `i(x)` should be interpreted as a mapping of the keypoint `x` to its respective image `i(x)`. So the notation `i(u)` refers to the image where keypoint `u` was detected, and the same for `i(v)`.

We are sorry for the slight confusion in the notation.

**Comment by Vincentqyw** [comment]
Got it! Thanks for your help:)
