### ISSUE TITLE
colmap::BundleAdjustmentOptions in bundle_optimizer_test.cc

### ISSUE THREAD

**Issue by XYZ-qiyh** [cvg/pixel-perfect-sfm#32]
Hello, thanks for your amazing work for using the learning technique to improve the accuracy of SfM !

There is no definition of `colmap::BundleAdjustmentOptions` in `bundle_optimizer_test.cc`, I found the definition of `colmap::BundleAdjustmentOptions` is in [colmap](https://github.com/colmap/colmap/blob/e180948665b03c4a12d45e2ca39a589f42fdbda6/src/optim/bundle_adjustment.h#L49).

When I use CMake to compile the the project, I just comment the line of  `#PIXSFM_ADD_TEST(bundle_optimizer_test src/bundle_optimizer_test.cc)` of `pixsfm/bundle_adjustment/CMakeLists.txt`. There is no error in compilation. 

The requirement of `pycolmap` is installed, but I don't  know `colmap` is necessary to run the `pixsfm`.

**Comment by Skydes** [comment]
Indeed this test file includes COLMAP:
https://github.com/cvg/pixel-perfect-sfm/blob/2f30a0ae0cce012901d4415316e54fdaaf8ab171/pixsfm/bundle_adjustment/src/bundle_optimizer_test.cc#L39

The documentation makes it very clear that installing COLMAP from source is required - pycolmap is __not__ sufficient and needs to be compiled from source too. Can you share the error message? What commit of COLMAP did you install?
