### ISSUE TITLE
Error in compilation types.cc.o

### ISSUE THREAD

**Issue by TWJianNuo** [cvg/pixel-perfect-sfm#35]
I run into the following issue while compilation:
`
    ERROR: Command errored out with exit status 1:
     command: /home/shengjie/anaconda3/envs/torch16/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/setup.py'"'"'; __file__='"'"'/home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/
    Complete output (158 lines):
    running develop
    running egg_info
    writing pixsfm.egg-info/PKG-INFO
    writing dependency_links to pixsfm.egg-info/dependency_links.txt
    writing top-level names to pixsfm.egg-info/top_level.txt
    reading manifest file 'pixsfm.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'pixsfm.egg-info/SOURCES.txt'
    running build_ext
    -- Found installed version of Eigen: /usr/lib/cmake/eigen3
    -- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
    -- Found required Ceres dependency: glog
    -- Found required Ceres dependency: gflags
    -- Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
    -- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   program_options
    --   filesystem
    --   system
    --   unit_test_framework
    -- Found Eigen
    --   Includes : /usr/include/eigen3
    -- Found FreeImage
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
    -- Found Glog
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
    CMake Warning (dev) at /usr/local/share/cmake-3.13/Modules/FindOpenGL.cmake:270 (message):
      Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
      available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.
    
      FindOpenGL found both a legacy GL library:
    
        OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
    
      and GLVND libraries for OpenGL and GLX:
    
        OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
        OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
    
      OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
      compatibility with CMake 3.10 and below the legacy GL library will be used.
    Call Stack (most recent call first):
      /usr/local/share/colmap/COLMAPConfig.cmake:103 (find_package)
      CMakeLists.txt:35 (find_package)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Found Glew
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
    -- HDF5: Using hdf5 compiler wrapper to determine C configuration
    -- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   system
    --   serialization
    -- pybind11 v2.8.1
    -- Configuring done
    CMake Warning at third-party/pybind11/tools/pybind11Tools.cmake:165 (add_library):
      Cannot generate a safe runtime search path for target _pixsfm because files
      in some directories may conflict with libraries in implicit directories:
    
        runtime library [libtbbmalloc.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
          /home/shengjie/anaconda3/envs/torch16/lib
        runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
          /home/shengjie/anaconda3/envs/torch16/lib
        runtime library [libGLU.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
          /home/shengjie/anaconda3/envs/torch16/lib
    
      Some of these libraries may not be found correctly.
    Call Stack (most recent call first):
      cmake/CMakeHelper.cmake:136 (pybind11_add_module)
      pixsfm/CMakeLists.txt:23 (PIXSFM_ADD_PYMODULE)
    
    
    -- Generating done
    -- Build files have been written to: /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/build/temp.linux-x86_64-3.6
    Scanning dependencies of target pixsfm
    [  9%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/base/src/graph.cc.o
    [  9%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/simple_logger.cc.o
    [  9%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/threading.cc.o
    [ 12%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/stringprintf.cc.o
    [ 15%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/glog.cc.o
    [ 18%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featurepatch.cc.o
    [ 25%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featureview.cc.o
    [ 25%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featuremap.cc.o
    [ 28%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featuremanager.cc.o
    [ 31%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featureset.cc.o
    [ 34%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/references.cc.o
    [ 37%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/keypoint_adjustment/src/keypoint_adjustment_options.cc.o
    [ 40%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/bundle_adjustment/src/bundle_adjustment_options.cc.o
    [ 43%] Linking CXX static library libpixsfm.a
    [ 43%] Built target pixsfm
    Scanning dependencies of target pypixsfm
    [ 46%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/base/bindings.cc.o
    [ 50%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/util/bindings.cc.o
    [ 53%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/callbacks.cc.o
    [ 56%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/residuals/bindings.cc.o
    [ 59%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/features/bindings.cc.o
    [ 62%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/keypoint_adjustment/bindings.cc.o
    [ 65%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/localization/bindings.cc.o
    [ 71%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/solver.cc.o
    [ 71%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/bundle_adjustment/bindings.cc.o
    [ 75%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/loss_functions.cc.o
    [ 78%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/cost_functions.cc.o
    [ 81%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/problem.cc.o
    [ 84%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/pyceres.cc.o
    [ 87%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/parameterization.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/types.cc.o
    In file included from /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/pixsfm/keypoint_adjustment/src/featuremetric_keypoint_optimizer.h:8,
                     from /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/pixsfm/keypoint_adjustment/bindings.cc:8:
    /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/pixsfm/base/src/parallel_optimizer.h:78:3: error: ‘RunParallel’ function uses ‘auto’ type specifier without trailing return type
       78 |   auto RunParallel(std::vector<int> problem_labels, Param&... parameters) {
          |   ^~~~
    /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/pixsfm/base/src/parallel_optimizer.h:78:3: note: deduced return type only available with ‘-std=c++14’ or ‘-std=gnu++14’
    In file included from /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/pixsfm/bundle_adjustment/src/costmap_extractor.h:16,
                     from /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/pixsfm/bundle_adjustment/bindings.cc:14:
    /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/pixsfm/base/src/parallel_optimizer.h:78:3: error: ‘RunParallel’ function uses ‘auto’ type specifier without trailing return type
       78 |   auto RunParallel(std::vector<int> problem_labels, Param&... parameters) {
          |   ^~~~
    /home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/pixsfm/base/src/parallel_optimizer.h:78:3: note: deduced return type only available with ‘-std=c++14’ or ‘-std=gnu++14’
    pixsfm/CMakeFiles/pypixsfm.dir/build.make:101: recipe for target 'pixsfm/CMakeFiles/pypixsfm.dir/keypoint_adjustment/bindings.cc.o' failed
    make[2]: *** [pixsfm/CMakeFiles/pypixsfm.dir/keypoint_adjustment/bindings.cc.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    pixsfm/CMakeFiles/pypixsfm.dir/build.make:114: recipe for target 'pixsfm/CMakeFiles/pypixsfm.dir/bundle_adjustment/bindings.cc.o' failed
    make[2]: *** [pixsfm/CMakeFiles/pypixsfm.dir/bundle_adjustment/bindings.cc.o] Error 1
    CMakeFiles/Makefile2:241: recipe for target 'pixsfm/CMakeFiles/pypixsfm.dir/all' failed
    make[1]: *** [pixsfm/CMakeFiles/pypixsfm.dir/all] Error 2
    Makefile:129: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/setup.py", line 126, in <module>
        package_data={'': ['configs/*.yaml']},
      File "/home/shengjie/anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/shengjie/anaconda3/envs/torch16/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/shengjie/anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/shengjie/anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/shengjie/anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/shengjie/anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/shengjie/anaconda3/envs/torch16/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/shengjie/anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/setup.py", line 55, in run
        self.build_extension(ext)
      File "/home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/setup.py", line 99, in build_extension
        cwd=self.build_temp)
      File "/home/shengjie/anaconda3/envs/torch16/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/shengjie/anaconda3/envs/torch16/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/setup.py'"'"'; __file__='"'"'/home/shengjie/Documents/supporting_projects/EMAwareFlow_related_projects/pixel-perfect-sfm/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
`

I tried the solution provided in [issue 9](https://github.com/cvg/pixel-perfect-sfm/issues/9), still, unresolved.
I tried gcc 8.4.0; gcc 9.4.0; and gcc 5.5.0. Also, I tried `AVX2_ENABLED=OFF pip install -e .` and branch [fix-parallel-optimizer](https://github.com/cvg/pixel-perfect-sfm/tree/fix-parallel-optimizer). 
It seems the gcc does not load c++ 14. But I am not sure. Any suggestion will be helpful!!!

**Comment by luffyfly** [comment]
Try "git checkout 82821395214e1acd58351bb173b38b69248ff63e", it worked for me.

**Comment by TWJianNuo** [comment]
Thanks, this works for me as well!
