### ISSUE TITLE
FeatureView(): incompatible function arguments

### ISSUE THREAD

**Issue by arsenal9971** [cvg/pixel-perfect-sfm#37]
When trying to run cell  [demo.ipynb](https://github.com/cvg/pixel-perfect-sfm/blob/main/demo.ipynb) I get the error message

`FeatureView(): incompatible function arguments. The following argument types are supported:...`

I am using hloc version 1.3 and the latest version of pixsfm. Do you know what does this error means?

Thanks!

**Comment by Phil26AT** [comment]
It is difficult to say without further info, but most probably you have installed [`pycolmap`](https://github.com/colmap/pycolmap)  via pypi, and thus the symbols do not match. As written in the README, make sure to install COLMAP and pycolmap from source.

**Comment by arsenal9971** [comment]
Yes, that fixes the problem, building `pycolmap` from source. Thanks!
