### ISSUE TITLE
Question of Eq.7 in paper

### ISSUE THREAD

**Issue by jing-yao** [cvg/pixel-perfect-sfm#38]
Thank you for open source this great project.
I have some question of the Eq.7  
![image](https://user-images.githubusercontent.com/72078493/160081155-acfae4dc-fbab-4bdd-8dd4-2e180b9f3ce0.png)
I just wonder what is the `μ` and the `f` in the Eq.(7)

**Comment by Skydes** [comment]
`μ^j` is the mean of the features `f` in the track `j` under the robust norm `γ` = it simply minimizes the total distance to all features.

**Comment by jing-yao** [comment]
Got it! Thanks for your help!
