### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by prajwalchidananda** [cvg/pixel-perfect-sfm#41]
[ 43%] Built target pixsfm
    Scanning dependencies of target pypixsfm
    [ 50%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/base/bindings.cc.o
    [ 87%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/features/bindings.cc.o
    [ 87%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/util/bindings.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/localization/bindings.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/keypoint_adjustment/bindings.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/residuals/bindings.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/bundle_adjustment/bindings.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/cost_functions.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/pyceres.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/solver.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/parameterization.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/callbacks.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/loss_functions.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/types.cc.o
    [ 90%] Building CXX object pixsfm/CMakeFiles/pypixsfm.dir/pyceres/problem.cc.o
    [ 93%] Linking CXX static library libpypixsfm.a
    [ 93%] Built target pypixsfm
    Scanning dependencies of target _pixsfm
    [ 96%] Building CXX object pixsfm/CMakeFiles/_pixsfm.dir/_pixsfm/bindings.cc.o
    [100%] Linking CXX shared module ../../../pixsfm/_pixsfm.cpython-38-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/local/lib/libceres.a(covariance_impl.cc.o): in function `ceres::internal::CovarianceImpl::GetCovarianceBlockInTangentOrAmbientSpace(double const*, double const*, bool, double*) const':
    covariance_impl.cc:(.text+0xa81b): undefined reference to `void Eigen::internal::call_dense_assignment_loop<Eigen::Matrix<double, -1, -1, 1, -1, -1>, Eigen::Matrix<double, -1, -1, 1, -1, -1>, Eigen::internal::assign_op<double, double> >(Eigen::Matrix<double, -1, -1, 1, -1, -1>&, Eigen::Matrix<double, -1, -1, 1, -1, -1> const&, Eigen::internal::assign_op<double, double> const&)'
    collect2: error: ld returned 1 exit status
    make[2]: *** [pixsfm/CMakeFiles/_pixsfm.dir/build.make:133: ../../pixsfm/_pixsfm.cpython-38-x86_64-linux-gnu.so] Error 1
    make[1]: *** [CMakeFiles/Makefile2:403: pixsfm/CMakeFiles/_pixsfm.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2
    /usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/prajwal.chidananda/pixel-perfect-sfm/setup.py", line 112, in <module>
        setup(
      File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/prajwal.chidananda/pixel-perfect-sfm/setup.py", line 55, in run
        self.build_extension(ext)
      File "/home/prajwal.chidananda/pixel-perfect-sfm/setup.py", line 98, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args,
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/prajwal.chidananda/pixel-perfect-sfm/setup.py'"'"'; __file__='"'"'/home/prajwal.chidananda/pixel-perfect-sfm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by prajwalchidananda** [comment]
Is this a known issue?

**Comment by Skydes** [comment]
This is a failure in Ceres, we don't use this function in pixsfm. Is your Eigen install maybe broken? Can you try to rebuild Ceres? What commit are you building with?

**Comment by Skydes** [comment]
For Ceres, can you try for example:
```diff
- RUN git checkout $(git describe --tags) # Checkout the latest release
+ RUN git checkout 2.1.0rc2
```
or some older commits?

**Comment by prajwalchidananda** [comment]
Tried the following configurations:

- Ceres: 2.1.0rc2, COLMAP: dev - Fails with same error
- Ceres: 2.1.0rc1, COLMAP: dev - Ceres fails to build
- Ceres: 2.0.0, COLMAP: dev - Fails with same error
- Ceres: 2.0.0, COLMAP: 3.6 - pycolmap fails to build

**Comment by prajwalchidananda** [comment]
I don't know if this is relevant, but I couldn't help but notice that the function mentioned in the error (GetCovarianceBlockInTangentOrAmbientSpace) is used in this recent COLMAP commit (https://github.com/colmap/colmap/commit/33e26924f950172751f044a89b964129b3728db8)

**Comment by Skydes** [comment]
In your Docker script, you will also need to build pycolmap from source. Do COLMAP and pycolmap build smoothly? does the build only crash for pixsfm?

**Comment by prajwalchidananda** [comment]
The reason I didn't explicitly include building pycolmap from source was because it was already included in requirements.txt; In any case, I added this to the Dockerfile and I still get the same error.
```
FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

MAINTAINER Prajwal Chidananda

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
  git \
  cmake \
  build-essential \
  libboost-program-options-dev \
  libboost-filesystem-dev \
  libboost-graph-dev \
  libboost-system-dev \
  libboost-test-dev \
  libeigen3-dev \
  libsuitesparse-dev \
  libfreeimage-dev \
  libmetis-dev \
  libgoogle-glog-dev \
  libgflags-dev \
  libglew-dev \
  qtbase5-dev \
  libqt5opengl5-dev \
  libcgal-dev \
  libatlas-base-dev \
  libsuitesparse-dev \
  libhdf5-dev \
  python-dev \
  python-setuptools \
  python3-pip \
  python3-dev \
  && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get clean && rm -rf /tmp/* /var/tmp/*

# Ceres solver
WORKDIR /opt
RUN git clone https://ceres-solver.googlesource.com/ceres-solver
WORKDIR /opt/ceres-solver
#RUN git checkout $(git describe --tags) # Checkout the latest release
RUN git checkout 2.1.0rc2
#RUN git checkout 2.1.0rc1
#RUN git checkout 2.0.0
RUN mkdir build
WORKDIR /opt/ceres-solver/build
RUN cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
RUN make -j
RUN make install

# Colmap
WORKDIR /opt
RUN git clone https://github.com/colmap/colmap.git
WORKDIR /opt/colmap
RUN git checkout dev
#RUN git checkout 3.6
#RUN git checkout 3.7
RUN mkdir build
WORKDIR /opt/colmap/build
RUN cmake ..
RUN make -j
RUN make install

# PyColmap
RUN pip3 install --upgrade git+https://github.com/colmap/pycolmap

# PixSfM
WORKDIR /
RUN git clone https://github.com/cvg/pixel-perfect-sfm --recursive
WORKDIR /pixel-perfect-sfm
RUN pip3 install -r requirements.txt
RUN git clone --recursive https://github.com/cvg/Hierarchical-Localization/
WORKDIR /pixel-perfect-sfm/Hierarchical-Localization
RUN pip3 install -e .
WORKDIR /pixel-perfect-sfm
RUN pip3 install -e .
```

- COLMAP and pycolmap build smoothly.
- Build only crashes in the last step of building PixSfM

**Comment by vdobro** [comment]
Hi @prajwalchidananda, I had the same problem but could solve it by building libeigen 3.4.0 from source instead of installing libeigen3-dev from the Ubuntu repository (as a step before building ceres-solver):

`RUN git clone --depth 1 --branch 3.4.0 https://gitlab.com/libeigen/eigen.git`
`RUN cd eigen && mkdir build && cd build && cmake .. && make install`

My Dockerfile was based on ubuntu:focal instead of nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04, but hope this helps in your case, too.

**Comment by prajwalchidananda** [comment]
Thanks @vdobro! Your suggestion worked. Others might find this working Dockerfile useful:
```
FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

MAINTAINER Prajwal Chidananda

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
  git \
  cmake \
  build-essential \
  libboost-program-options-dev \
  libboost-filesystem-dev \
  libboost-graph-dev \
  libboost-system-dev \
  libboost-test-dev \
  libsuitesparse-dev \
  libfreeimage-dev \
  libmetis-dev \
  libgoogle-glog-dev \
  libgflags-dev \
  libglew-dev \
  qtbase5-dev \
  libqt5opengl5-dev \
  libcgal-dev \
  libatlas-base-dev \
  libsuitesparse-dev \
  libhdf5-dev \
  python-dev \
  python-setuptools \
  python3-pip \
  python3-dev \
  && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get clean && rm -rf /tmp/* /var/tmp/*

# Eigen
WORKDIR /opt
RUN git clone --depth 1 --branch 3.4.0 https://gitlab.com/libeigen/eigen.git
RUN cd eigen && mkdir build && cd build && cmake .. && make install

# Ceres solver
WORKDIR /opt
RUN git clone https://ceres-solver.googlesource.com/ceres-solver
WORKDIR /opt/ceres-solver
RUN git checkout 2.1.0rc2
RUN mkdir build
WORKDIR /opt/ceres-solver/build
RUN cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
RUN make -j
RUN make install

# Colmap
WORKDIR /opt
RUN git clone https://github.com/colmap/colmap.git
WORKDIR /opt/colmap
RUN git checkout dev
RUN mkdir build
WORKDIR /opt/colmap/build
RUN cmake ..
RUN make -j
RUN make install

# PixSfM
WORKDIR /
RUN git clone https://github.com/cvg/pixel-perfect-sfm --recursive
WORKDIR /pixel-perfect-sfm
RUN pip3 install -r requirements.txt
RUN git clone --recursive https://github.com/cvg/Hierarchical-Localization/
WORKDIR /pixel-perfect-sfm/Hierarchical-Localization
RUN pip3 install -e .
WORKDIR /pixel-perfect-sfm
RUN pip3 install -e .
```

**Comment by prajwalchidananda** [comment]
@Skydes Maybe it should be mentioned somewhere in the instructions that eigen is to be installed from source?

**Comment by Skydes** [comment]
This seems related to Ceres rather than pixsfm. `libeigen3-dev` installs 3.3.7, which is the minimum version according to the Ceres doc. Perhaps Ceres actually now requires >=3.4?

**Comment by Phil26AT** [comment]
Actually this was a linking error on our side, thanks for pointing this out @prajwalchidananda!

I pushed a fix to [`fix-undefined-references`](https://github.com/cvg/pixel-perfect-sfm/tree/fix-undefined-references).

**Comment by MACILLAS** [comment]
> Thanks [@vdobro](https://github.com/vdobro)! Your suggestion worked. Others might find this working Dockerfile useful:
> 
> ```
> FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04
> 
> MAINTAINER Prajwal Chidananda
> 
> ENV DEBIAN_FRONTEND=noninteractive
> 
> RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
>   git \
>   cmake \
>   build-essential \
>   libboost-program-options-dev \
>   libboost-filesystem-dev \
>   libboost-graph-dev \
>   libboost-system-dev \
>   libboost-test-dev \
>   libsuitesparse-dev \
>   libfreeimage-dev \
>   libmetis-dev \
>   libgoogle-glog-dev \
>   libgflags-dev \
>   libglew-dev \
>   qtbase5-dev \
>   libqt5opengl5-dev \
>   libcgal-dev \
>   libatlas-base-dev \
>   libsuitesparse-dev \
>   libhdf5-dev \
>   python-dev \
>   python-setuptools \
>   python3-pip \
>   python3-dev \
>   && \
>   rm -rf /var/lib/apt/lists/* && \
>   apt-get clean && rm -rf /tmp/* /var/tmp/*
> 
> # Eigen
> WORKDIR /opt
> RUN git clone --depth 1 --branch 3.4.0 https://gitlab.com/libeigen/eigen.git
> RUN cd eigen && mkdir build && cd build && cmake .. && make install
> 
> # Ceres solver
> WORKDIR /opt
> RUN git clone https://ceres-solver.googlesource.com/ceres-solver
> WORKDIR /opt/ceres-solver
> RUN git checkout 2.1.0rc2
> RUN mkdir build
> WORKDIR /opt/ceres-solver/build
> RUN cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
> RUN make -j
> RUN make install
> 
> # Colmap
> WORKDIR /opt
> RUN git clone https://github.com/colmap/colmap.git
> WORKDIR /opt/colmap
> RUN git checkout dev
> RUN mkdir build
> WORKDIR /opt/colmap/build
> RUN cmake ..
> RUN make -j
> RUN make install
> 
> # PixSfM
> WORKDIR /
> RUN git clone https://github.com/cvg/pixel-perfect-sfm --recursive
> WORKDIR /pixel-perfect-sfm
> RUN pip3 install -r requirements.txt
> RUN git clone --recursive https://github.com/cvg/Hierarchical-Localization/
> WORKDIR /pixel-perfect-sfm/Hierarchical-Localization
> RUN pip3 install -e .
> WORKDIR /pixel-perfect-sfm
> RUN pip3 install -e .
> ```

Idk who's still working on this in 2025 :P Had to pin down a few more versions but here is the Dockerfile that worked for me (Ubuntu 20 NVIDIA 3090)

```
FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

MAINTAINER Prajwal Chidananda

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
  git \
  cmake \
  wget \
  build-essential \
  libboost-program-options-dev \
  libboost-filesystem-dev \
  libboost-graph-dev \
  libboost-system-dev \
  libboost-test-dev \
  libsuitesparse-dev \
  libflann-dev \
  libfreeimage-dev \
  libmetis-dev \
  libgoogle-glog-dev \
  libgflags-dev \
  libsqlite3-dev \
  libglew-dev \
  qtbase5-dev \
  libqt5opengl5-dev \
  libcgal-dev \
  libatlas-base-dev \
  libsuitesparse-dev \
  libhdf5-dev \
  python-dev \
  python-setuptools \
  python3-pip \
  python3-dev \
  ninja-build \
  && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get clean && rm -rf /tmp/* /var/tmp/*

# Eigen
WORKDIR /opt
RUN git clone --depth 1 --branch 3.4.0 https://gitlab.com/libeigen/eigen.git
RUN cd eigen && mkdir build && cd build && cmake .. && make install

# Ceres solver
WORKDIR /opt
RUN git clone https://ceres-solver.googlesource.com/ceres-solver
WORKDIR /opt/ceres-solver
RUN git checkout 2.1.0rc2
RUN mkdir build
WORKDIR /opt/ceres-solver/build
RUN cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
RUN make -j
RUN make install

# Colmap
WORKDIR /opt
RUN git clone https://github.com/colmap/colmap.git
WORKDIR /opt/colmap
RUN git checkout 3.8
RUN mkdir build
WORKDIR /opt/colmap/build
RUN cmake .. -DCUDA_ENABLED=ON -DCMAKE_CUDA_ARCHITECTURES="70;72;75;80;86" -GNinja
#RUN make -j
#RUN make install
RUN ninja && ninja install

# PixSfM
WORKDIR /
RUN git clone https://github.com/cvg/pixel-perfect-sfm --recursive
WORKDIR /pixel-perfect-sfm
RUN pip3 install -r requirements.txt
RUN git clone --recursive https://github.com/cvg/Hierarchical-Localization/
WORKDIR /pixel-perfect-sfm/Hierarchical-Localization
RUN git checkout v1.4
RUN pip3 install -e .
WORKDIR /pixel-perfect-sfm
RUN pip3 install -e .
RUN pip3 install pycolmap==0.4.0
```

**Comment by GibsDev** [comment]
I had to bump the pycolmap version to 0.6.0 and enable the 89 architecture for a 4090:

```
FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

MAINTAINER Prajwal Chidananda

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
  git \
  cmake \
  wget \
  build-essential \
  libboost-program-options-dev \
  libboost-filesystem-dev \
  libboost-graph-dev \
  libboost-system-dev \
  libboost-test-dev \
  libsuitesparse-dev \
  libflann-dev \
  libfreeimage-dev \
  libmetis-dev \
  libgoogle-glog-dev \
  libgflags-dev \
  libsqlite3-dev \
  libglew-dev \
  qtbase5-dev \
  libqt5opengl5-dev \
  libcgal-dev \
  libatlas-base-dev \
  libsuitesparse-dev \
  libhdf5-dev \
  python-dev \
  python-setuptools \
  python3-pip \
  python3-dev \
  ninja-build \
  && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get clean && rm -rf /tmp/* /var/tmp/*

# Eigen
WORKDIR /opt
RUN git clone --depth 1 --branch 3.4.0 https://gitlab.com/libeigen/eigen.git
RUN cd eigen && mkdir build && cd build && cmake .. && make install

# Ceres solver
WORKDIR /opt
RUN git clone https://ceres-solver.googlesource.com/ceres-solver
WORKDIR /opt/ceres-solver
RUN git checkout 2.1.0rc2
RUN mkdir build
WORKDIR /opt/ceres-solver/build
RUN cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
RUN make -j
RUN make install

# Colmap
WORKDIR /opt
RUN git clone https://github.com/colmap/colmap.git
WORKDIR /opt/colmap
RUN git checkout 3.8
RUN mkdir build
WORKDIR /opt/colmap/build
RUN cmake .. -DCUDA_ENABLED=ON -DCMAKE_CUDA_ARCHITECTURES="70;72;75;80;86;89" -GNinja
#RUN make -j
#RUN make install
RUN ninja && ninja install

# PixSfM
WORKDIR /
RUN git clone https://github.com/cvg/pixel-perfect-sfm --recursive
WORKDIR /pixel-perfect-sfm
RUN pip3 install -r requirements.txt
RUN git clone --recursive https://github.com/cvg/Hierarchical-Localization/
WORKDIR /pixel-perfect-sfm/Hierarchical-Localization
RUN git checkout v1.4
RUN pip3 install -e .
WORKDIR /pixel-perfect-sfm
RUN pip3 install -e .
RUN pip3 install pycolmap==0.6.0
```
