### ISSUE TITLE
Specify Camera Model?

### ISSUE THREAD

**Issue by cduguet** [cvg/pixel-perfect-sfm#48]
I would like to specify the camera model for the reconstruction model. I've seen [pycolmap accepts a `camera_model` parameter in its `import_images` function](https://github.com/colmap/pycolmap/blob/34541c45dce80bf18076dd158d9e7380fe4a16cd/pipeline.cc#L31) , which is called by [hloc's `import_images`](https://github.com/cvg/Hierarchical-Localization/blob/e8ea8a25b297bae2e058abfb294335219d9f55ad/hloc/reconstruction.py#L25). In PixSfM it seems we can pass arguments for hloc's main, but hloc only knows how to manage `camera_mode` and not `camera_model`.

If I, for instance, would like to create and refine end-to-end a reconstruction with camera model `OPENCV` using (using hloc and not colmap). How should I do it? 

PS: I could be posting this on hloc's issues, but since using pixsfm is my end goal maybe there is a better way to do it from here, that I'm not seeing.

Thank you!

**Comment by Skydes** [comment]
Does [this PR](https://github.com/cvg/Hierarchical-Localization/pull/179) solve your issue?

**Comment by Skydes** [comment]
This is now fully supported by hloc via https://github.com/cvg/Hierarchical-Localization/pull/210. An example is given here: https://github.com/cvg/Hierarchical-Localization/issues/219#issuecomment-1219213026
