### ISSUE TITLE
Installation issue: No module named 'pixsfm._pixsfm._base'

### ISSUE THREAD

**Issue by manasi9610** [cvg/pixel-perfect-sfm#60]
I'm facing an issue while importing pixsfm . 
Following is the error- 

`>>> from pixsfm.util.visualize import init_image, plot_points2D
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/pixelperf/pixel-perfect-sfm/pixsfm/__init__.py", line 18, in <module>
    from . import (  # noqa F403
  File "/home/ubuntu/pixelperf/pixel-perfect-sfm/pixsfm/base/__init__.py", line 1, in <module>
    from .._pixsfm._base import *  # noqa F403
ModuleNotFoundError: No module named 'pixsfm._pixsfm._base'`

**Comment by manasi9610** [comment]
<img width="769" alt="Screenshot 2022-05-26 at 8 42 21 PM" src="https://user-images.githubusercontent.com/90911390/170517956-0dd6e48e-9d85-4623-89af-c72f95ba74a8.png">

It is installed, still getting this error

**Comment by manasi9610** [comment]
The error - `from .._pixsfm._base import *  # noqa F403` , its trying to import the  `<_base` module. However, I checked the `_pixsfm` folder, there is no `_base` file

**Comment by TITAINc** [comment]
Hi @manasi9610 ,
 How did you solve this problem?

**Comment by woshiluozhi** [comment]
Hello @manasi9610 , I also met the same problem. How to solve ”No module named 'pixsfm._pixsfm._base“?
