### ISSUE TITLE
cannot get s2dnet_weights.pth

### ISSUE THREAD

**Issue by aipanpan123** [cvg/pixel-perfect-sfm#61]
when refiner = PixSfM(), 

super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ai/workspace/pixel-perfect-sfm/pixsfm/features/models/checkpoints/s2dnet_weights.pth'

**Comment by Phil26AT** [comment]
Hi, sorry for the late reply. Usually the weights should be downloaded automatically, but you can also manually get them from [https://www.dropbox.com/s/hnv51iwu4hn82rj/s2dnet_weights.pth](https://www.dropbox.com/s/hnv51iwu4hn82rj/s2dnet_weights.pth).
