### ISSUE TITLE
error in bundle_adjustment

### ISSUE THREAD

**Issue by CoCa520** [cvg/pixel-perfect-sfm#64]
I met the ba problem，how can I due with it?

this is the error message:
Reconstruction:
	num_reg_images = 135
	num_cameras = 135
	num_points3D = 24356
	num_observations = 142783
	mean_track_length = 5.86233
	mean_observations_per_image = 1057.65
	mean_reprojection_error = 1.31232
	num_input_images = 143
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/sfm_loc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/sfm_loc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/workspace/projects/python/pixel-perfect-sfm/pixsfm/refine_hloc.py", line 210, in <module>
    args.matches_path, cache_path=args.cache_path)
  File "/home/user/workspace/projects/python/pixel-perfect-sfm/pixsfm/refine_hloc.py", line 146, in reconstruction
    feature_manager=feature_manager, **hloc_args)
  File "/home/user/workspace/projects/python/pixel-perfect-sfm/pixsfm/refine_hloc.py", line 59, in run
    cache_path=cache_path, feature_manager=feature_manager)
  File "/home/user/workspace/projects/python/pixel-perfect-sfm/pixsfm/refine_colmap.py", line 94, in run_ba
    reconstruction, feature_manager)
  File "/home/user/workspace/projects/python/pixel-perfect-sfm/pixsfm/bundle_adjustment/main.py", line 95, in refine_multilevel
    problem_setup)
  File "/home/user/workspace/projects/python/pixel-perfect-sfm/pixsfm/bundle_adjustment/main.py", line 267, in refine
    feature_set, ref_extractor)
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: pixsfm._pixsfm._bundle_adjustment.CostMapExtractor, arg0: List[int], arg1: colmap::Reconstruction, arg2: pixsfm::FeatureSet<half_float::half>, arg3: pixsfm._pixsfm._bundle_adjustment.ReferenceExtractor) -> Tuple[pixsfm::FeatureSet<half_float::half>, std::unordered_map<unsigned long, pixsfm::Reference, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, pixsfm::Reference> > >]
    2. (self: pixsfm._pixsfm._bundle_adjustment.CostMapExtractor, arg0: List[int], arg1: colmap::Reconstruction, arg2: pixsfm::FeatureSet<float>, arg3: pixsfm._pixsfm._bundle_adjustment.ReferenceExtractor) -> Tuple[pixsfm::FeatureSet<float>, std::unordered_map<unsigned long, pixsfm::Reference, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, pixsfm::Reference> > >]
    3. (self: pixsfm._pixsfm._bundle_adjustment.CostMapExtractor, arg0: List[int], arg1: colmap::Reconstruction, arg2: pixsfm::FeatureSet<double>, arg3: pixsfm._pixsfm._bundle_adjustment.ReferenceExtractor) -> Tuple[pixsfm::FeatureSet<double>, std::unordered_map<unsigned long, pixsfm::Reference, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, pixsfm::Reference> > >]

Invoked with: <pixsfm._pixsfm._bundle_adjustment.CostMapExtractor object at 0x7f4492090a70>, [-1, 0, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0,...,  298], <Reconstruction 'num_reg_images=135, num_cameras=135, num_points3D=24356, num_observations=142783'>, <pixsfm._pixsfm._features.FeatureSet_f16 object at 0x7f4492efb0f0>, <pixsfm._pixsfm._bundle_adjustment.ReferenceExtractor object at 0x7f449b3cffb0>

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

**Comment by XuqianRen** [comment]
Hi, I meet the same error, have you solved it?

**Comment by ayehninnkhine** [comment]
Hi, I have the same error too.Is there any solution for this?

**Comment by ayehninnkhine** [comment]
Hi, I got this. We need to install pycolmap from source. 
https://github.com/colmap/pycolmap
