### ISSUE TITLE
Build error : ‘attribute_error’ is not a member of ‘py’

### ISSUE THREAD

**Issue by belkahorry** [cvg/pixel-perfect-sfm#65]
Thanks for sharing these excellent work.
This strange error occured during pip installing, i found no info about it on google

ubuntu 20.04
gcc 9.4.0
cmake 3.21.6
ceres 2.2.0
python 3.9.7

Building log:
-- Generating done
    -- Build files have been written to: /home/horry/pixel-perfect-sfm/build/temp.linux-x86_64-3.9
    [  3%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/base/src/graph.cc.o
    [  6%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/simple_logger.cc.o
    [  9%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/threading.cc.o
    [ 12%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/stringprintf.cc.o
    [ 15%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featurepatch.cc.o
    [ 18%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/glog.cc.o
    [ 21%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featuremap.cc.o
    [ 25%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featureview.cc.o
    [ 28%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featuremanager.cc.o
    [ 31%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/references.cc.o
    [ 34%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/bundle_adjustment/src/bundle_adjustment_options.cc.o
    [ 37%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featureset.cc.o
    [ 40%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/keypoint_adjustment/src/keypoint_adjustment_options.cc.o
    In file included from /home/horry/pixel-perfect-sfm/pixsfm/features/src/references.h:2,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/references.cc:1:
    /home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h: In lambda function:
    _**/home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h:222:21: error: ‘attribute_error’ is not a member of ‘py’
      222 |           throw py::attribute_error(ss.str());**_
          |                     ^~~~~~~~~~~~~~~
    In file included from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featuremap.h:2,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featuremap.cc:1:
    /home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h: In lambda function:
    _**/home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h:222:21: error: ‘attribute_error’ is not a member of ‘py’
      222 |           throw py::attribute_error(ss.str());**_
          |                     ^~~~~~~~~~~~~~~
    In file included from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featureview.h:2,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featureview.cc:1:
    /home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h: In lambda function:
    _**/home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h:222:21: error: ‘attribute_error’ is not a member of ‘py’
      222 |           throw py::attribute_error(ss.str());**_
          |                     ^~~~~~~~~~~~~~~
    In file included from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featurepatch.h:3,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featurepatch.cc:1:
    /home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h: In lambda function:
    _**/home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h:222:21: error: ‘attribute_error’ is not a member of ‘py’
      222 |           throw py::attribute_error(ss.str());**_
          |                     ^~~~~~~~~~~~~~~
    In file included from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featureset.h:3,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featureset.cc:1:
    /home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h: In lambda function:
    _**/home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h:222:21: error: ‘attribute_error’ is not a member of ‘py’
      222 |           throw py::attribute_error(ss.str());**_
          |                     ^~~~~~~~~~~~~~~
    In file included from /home/horry/pixel-perfect-sfm/pixsfm/keypoint_adjustment/src/keypoint_adjustment_options.h:2,
                     from /home/horry/pixel-perfect-sfm/pixsfm/keypoint_adjustment/src/keypoint_adjustment_options.cc:1:
    /home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h: In lambda function:
    _**/home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h:222:21: error: ‘attribute_error’ is not a member of ‘py’
      222 |           throw py::attribute_error(ss.str());**_
          |                     ^~~~~~~~~~~~~~~
    In file included from /home/horry/pixel-perfect-sfm/pixsfm/bundle_adjustment/src/bundle_adjustment_options.h:2,
                     from /home/horry/pixel-perfect-sfm/pixsfm/bundle_adjustment/src/bundle_adjustment_options.cc:1:
    /home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h: In lambda function:
    _**/home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h:222:21: error: ‘attribute_error’ is not a member of ‘py’
      222 |           throw py::attribute_error(ss.str());**_
          |                     ^~~~~~~~~~~~~~~
    In file included from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featuremanager.h:2,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featuremanager.cc:7:
    /home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h: In lambda function:
    _**/home/horry/pixel-perfect-sfm/pixsfm/_pixsfm/src/helpers.h:222:21: error: ‘attribute_error’ is not a member of ‘py’
      222 |           throw py::attribute_error(ss.str());**_
          |                     ^~~~~~~~~~~~~~~
    In file included from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featureview.cc:3:
    /home/horry/pixel-perfect-sfm/pixsfm/util/src/memory.h: In function ‘long long int pixsfm::NumNonZerosJacobian(const ceres::Problem*)’:
    /home/horry/pixel-perfect-sfm/pixsfm/util/src/memory.h:59:74: warning: ‘int ceres::Problem::ParameterBlockLocalSize(const double*) const’ is deprecated: LocalParameterizations are deprecated. Use ParameterBlockTangentSize instead. [-Wdeprecated-declarations]
       59 |         num_active_params += problem->ParameterBlockLocalSize(param_block);
          |                                                                          ^
    In file included from /usr/local/include/ceres/ceres.h:66,
                     from /home/horry/pixel-perfect-sfm/pixsfm/base/src/interpolation.h:15,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featurepatch.h:20,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featuremap.h:24,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featureview.h:23,
                     from /home/horry/pixel-perfect-sfm/pixsfm/features/src/featureview.cc:1:
    /usr/local/include/ceres/problem.h:494:7: note: declared here
      494 |   int ParameterBlockLocalSize(const double* values) const;
          |       ^~~~~~~~~~~~~~~~~~~~~~~
    make[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:216：pixsfm/CMakeFiles/pixsfm.dir/features/src/references.cc.o] error 1
    make[2]: *** waiting for unfinished work....
    make[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:230：pixsfm/CMakeFiles/pixsfm.dir/keypoint_adjustment/src/keypoint_adjustment_options.cc.o] error 1
    make[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:146：pixsfm/CMakeFiles/pixsfm.dir/features/src/featurepatch.cc.o] error 1
    make[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:244：pixsfm/CMakeFiles/pixsfm.dir/bundle_adjustment/src/bundle_adjustment_options.cc.o] error 1
    make[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:160：pixsfm/CMakeFiles/pixsfm.dir/features/src/featuremap.cc.o] error 1
    make[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:188：pixsfm/CMakeFiles/pixsfm.dir/features/src/featureview.cc.o] error 1
    make[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:202：pixsfm/CMakeFiles/pixsfm.dir/features/src/featureset.cc.o] error 1
    make[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:174：pixsfm/CMakeFiles/pixsfm.dir/features/src/featuremanager.cc.o] error 1
    make[1]: *** [CMakeFiles/Makefile2:421：pixsfm/CMakeFiles/pixsfm.dir/all] error 2
    make: *** [Makefile:136：all] error 2
    Traceback......etc.....
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/horry/anaconda3/envs/pytorch/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/horry/pixel-perfect-sfm/setup.py'"'"'; __file__='"'"'/home/horry/pixel-perfect-sfm/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

Thanks for any advice

**Comment by yuxiang-wen** [comment]
收到，谢谢

**Comment by belkahorry** [comment]
> 

I solved this problem by building it in a simplified env
