### ISSUE TITLE
Faster loading of SuperGlue weights

### ISSUE THREAD

**Issue by ThomasParistech** [cvg/pixel-perfect-sfm#69]
Each time I run a script that calls the matcher, it takes about 20s to load SuperGlue model ("outdoor" weights).
Is there a way to better reuse cache between consecutive runs? Or is it that big in memory?

For instance loading S2DNet checkpoint at _/dependencies/pixel-perfect-sfm/pixsfm/features/models/checkpoints/s2dnet_weights.pth._ is instantaneous 

Many thanks

**Comment by Skydes** [comment]
This is more of an issue related to hloc. I am not sure what could be happening there as the SuperGlue weights are actually smaller on disk (46M vs 59M). An easy fix for now is to pass `model` as an extra param to `hloc.match_features.match_from_paths`.

**Comment by ThomasParistech** [comment]
Is it the call to Model.eval() that is slow?
Apart from that _match_from_paths_ merely loads the model and pushes it to the GPU. 
```
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    Model = dynamic_load(matchers, conf['model']['name'])
    model = Model(conf['model']).eval().to(device)
```

**Comment by Skydes** [comment]
Moving the model to GPU is probably the culprit - for S2DNet we trim the model and only move a few layers to GPU. Caching it should help.

**Comment by ThomasParistech** [comment]
In  _pixsfm/features/models/s2dnet.py_  it seems like the data is not loaded on the GPU
```
line 115.  
state_dict = torch.load(path, map_location='cpu')['state_dict']```

To sum up, how should we load the matcher weights or which trimming operation should be applied to the weights before caching them?

**Comment by Skydes** [comment]
There is no trimming involved with SuperGlue - we load the full model as you reference it above. For S2DNet, we move the model to GPU here:
https://github.com/cvg/pixel-perfect-sfm/blob/39bebc498b2fa71702e1b6d4799aec8bed72c42d/pixsfm/features/extractor.py#L78
