### ISSUE TITLE
cannot run  " pip install -e . " to install pixsfm

### ISSUE THREAD

**Issue by mrKornWij** [cvg/pixel-perfect-sfm#72]
I try to build pixsfm but it stills show this error . How to solve this error?
![error install](https://user-images.githubusercontent.com/88375996/192450434-54ad1241-25c9-4c5d-b01a-7e04dfff7765.png)

**Comment by mrKornWij** [comment]
I tried to build pycolmap from source and it remains the same error.

**Comment by mrKornWij** [comment]
@Phil26AT  here is full lo after running 'pip install -e .'

![1problem](https://user-images.githubusercontent.com/88375996/192528997-9d890e15-bb13-4925-92ce-59bd0ebdcd9b.png)

![problem2](https://user-images.githubusercontent.com/88375996/192529089-24dce10d-2b32-4fdc-8062-2c5101f62a90.png)

![problem3](https://user-images.githubusercontent.com/88375996/192529135-64a44be8-08ed-4d0e-9fca-bf2f44146bae.png)

![problem5](https://user-images.githubusercontent.com/88375996/192529220-3e909590-9d55-454a-bbda-02c1b5b22bf1.png)

![problem6](https://user-images.githubusercontent.com/88375996/192529283-f211906f-07ff-40b0-8d07-be8e8da6a8ba.png)

**Comment by Phil26AT** [comment]
Hi @mrKornWij, thanks for providing the log files. Your installation cannot find COLMAP. Have you already installed COLMAP as a library? After building, this can be done with `sudo make install`. Then, there should exist a folder `/usr/local/lib/colmap`.

**Comment by mrKornWij** [comment]
@Phil26AT Umm, maybe my laptop does not support colmap. So I changed to my computer that has installed colmap then I've tried to install again. but I still get error after using "pip install -e ." command. it shown errors below
![isl2errorpix1](https://user-images.githubusercontent.com/88375996/192721619-c24cad3c-4648-4263-ad1d-a07afcf21dda.png)

![isl2errorpix2](https://user-images.githubusercontent.com/88375996/192721681-47be43d4-e893-4acd-87ef-31c31d3a013c.png)

![pixisl2error3](https://user-images.githubusercontent.com/88375996/192721742-f58c5ffd-5836-4b6a-8d50-5aefa7cdf022.png)

![isl2errorpix5](https://user-images.githubusercontent.com/88375996/192721838-0cf0e746-2c65-4c43-a108-4d5e050e9d7a.png)

![pixerror6isl2](https://user-images.githubusercontent.com/88375996/192721900-91135a92-8f69-45e1-bf04-9f8fa79a14ff.png)

![isl2eroro7](https://user-images.githubusercontent.com/88375996/192721955-2c4b4e8d-c351-4843-8a31-25b115ab9681.png)

![isl2error8](https://user-images.githubusercontent.com/88375996/192722037-50b34055-4fbd-45ca-b825-12b43a242996.png)

![error9isl2](https://user-images.githubusercontent.com/88375996/192722116-d6b7be26-4e4e-4133-a344-ca87a64e6ebc.png)

**Comment by Skydes** [comment]
@mrKornWij Already solved in https://github.com/cvg/pixel-perfect-sfm/issues/66: try Ceres <=2.1.0 or PR https://github.com/cvg/pixel-perfect-sfm/pull/68.

**Comment by mrKornWij** [comment]
thank you so much!
