### ISSUE TITLE
Demo not working properly

### ISSUE THREAD

**Issue by Xiaobin-Jiang** [cvg/pixel-perfect-sfm#8]
Hi,  thank you for your great work!
I try to run the demo, but the program stops running at Featureview().  

I got the following error：

Traceback (most recent call last):
  File "demo_test.py", line 47, in <module>
refined, sfm_outputs = sfm.reconstruction(ref_dir, images, sfm_pairs, features, matches, image_list=references)
  File "/home/algo/Projects/pixel-sfm/pixel-perfect-sfm/pixsfm/refine_hloc.py", line 143, in reconstruction
    return self.run(
  File "/home/algo/Projects/pixel-sfm/pixel-perfect-sfm/pixsfm/refine_hloc.py", line 57, in run
    reconstruction, ba_data, feature_manager = self.run_ba(
  File "/home/algo/Projects/pixel-sfm/pixel-perfect-sfm/pixsfm/refine_colmap.py", line 93, in run_ba
    ba_data = self.bundle_adjuster.refine_multilevel(
  File "/home/algo/Projects/pixel-sfm/pixel-perfect-sfm/pixsfm/bundle_adjustment/main.py", line 93, in refine_multilevel
    out = self.refine(
  File "/home/algo/Projects/pixel-sfm/pixel-perfect-sfm/pixsfm/bundle_adjustment/main.py", line 129, in refine
    feature_view = features.FeatureView(
TypeError: FeatureView(): incompatible function arguments. The following argument types are supported:
    1. (feature_set: pixsfm._pixsfm._features.FeatureSet_f16, reconstruction: colmap::Reconstruction) -> pixsfm._pixsfm._features.FeatureView_f16
    2. (feature_set: pixsfm._pixsfm._features.FeatureSet_f16, graph: pixsfm._pixsfm._base.Graph) -> pixsfm._pixsfm._features.FeatureView_f16
    3. (feature_set: pixsfm._pixsfm._features.FeatureSet_f16, graph: pixsfm._pixsfm._base.Graph, required_nodes: Set[int]) -> pixsfm._pixsfm._features.FeatureView_f16
    4. (feature_set: pixsfm._pixsfm._features.FeatureSet_f16, image_names: Set[str]) -> pixsfm._pixsfm._features.FeatureView_f16
    5. (feature_set: pixsfm._pixsfm._features.FeatureSet_f16, reconstruction: colmap::Reconstruction, point3D_ids: Set[int]) -> pixsfm._pixsfm._features.FeatureView_f16
    6. (feature_set: pixsfm._pixsfm._features.FeatureSet_f64, reconstruction: colmap::Reconstruction) -> pixsfm._pixsfm._features.FeatureView_f64
    7. (feature_set: pixsfm._pixsfm._features.FeatureSet_f64, graph: pixsfm._pixsfm._base.Graph) -> pixsfm._pixsfm._features.FeatureView_f64
    8. (feature_set: pixsfm._pixsfm._features.FeatureSet_f64, graph: pixsfm._pixsfm._base.Graph, required_nodes: Set[int]) -> pixsfm._pixsfm._features.FeatureView_f64
    9. (feature_set: pixsfm._pixsfm._features.FeatureSet_f64, image_names: Set[str]) -> pixsfm._pixsfm._features.FeatureView_f64
    10. (feature_set: pixsfm._pixsfm._features.FeatureSet_f64, reconstruction: colmap::Reconstruction, point3D_ids: Set[int]) -> pixsfm._pixsfm._features.FeatureView_f64
    11. (feature_set: pixsfm._pixsfm._features.FeatureSet_f32, reconstruction: colmap::Reconstruction) -> pixsfm._pixsfm._features.FeatureView_f32
    12. (feature_set: pixsfm._pixsfm._features.FeatureSet_f32, graph: pixsfm._pixsfm._base.Graph) -> pixsfm._pixsfm._features.FeatureView_f32
    13. (feature_set: pixsfm._pixsfm._features.FeatureSet_f32, graph: pixsfm._pixsfm._base.Graph, required_nodes: Set[int]) -> pixsfm._pixsfm._features.FeatureView_f32
    14. (feature_set: pixsfm._pixsfm._features.FeatureSet_f32, image_names: Set[str]) -> pixsfm._pixsfm._features.FeatureView_f32
    15. (feature_set: pixsfm._pixsfm._features.FeatureSet_f32, reconstruction: colmap::Reconstruction, point3D_ids: Set[int]) -> pixsfm._pixsfm._features.FeatureView_f32

Invoked with: <pixsfm._pixsfm._features.FeatureSet_f16 object at 0x7f716642f530>, <Reconstruction 'num_reg_images=10, num_cameras=10, num_points3D=1856, num_observations=8069'>

128 feature_view = features.FeatureView(
129     feature_set,
130     reconstruction
131 )

I printed out the types of the following two parameters, which are  <class 'pixsfm._pixsfm._features.FeatureSet_f16'> and <class 'pycolmap.Reconstruction'>.
Is the error due to the wrong type of parameter for reconstruction? how can i solve this problem?

Thanks in advance!

my environment：
Ubuntu 16.04
Python 3.8

**Comment by Skydes** [comment]
Did you install pycolmap from the PyPI wheels? This is currently not supported, pixsfm requires that pycolmap is built from source with the same COLMAP installation: `pip install --upgrade git+https://github.com/colmap/pycolmap`

**Comment by Xiaobin-Jiang** [comment]
Hi @Skydes. Thanks for the quick reply. 
I did install pycolmap from PyPI wheels.， I now install pycolmap through the source code, the demo can work normally.
Thanks for your guidance.

I have a suggestion,  pixsfm requires Python >=3.8,  because pycolmap cannot be installed on python 3.6.

**Comment by Skydes** [comment]
We provide pycolmap Linux wheels compiled for Python >=3.7 only but pycolmap can be built from source for Python >=3.5, so pixsfm should work with Python 3.6. I have improved the doc in https://github.com/cvg/pixel-perfect-sfm/commit/cbae8ef09e04a58a7d36f39d1d9779874a808ebd.
