### ISSUE TITLE
Question about Section 4.1 of the paper

### ISSUE THREAD

**Issue by lucaBartolomei** [cvg/pixel-perfect-sfm#82]
Hi! 

Thanks a lot for this amazing work! I would have a question regarding one part of the paper. 
In Section 4.1 ("Learned representation"), it is stated:
> Our experiments show that multiple off-the-shelf dense local descriptors can result in highly accurate refinements. However, our formulation can also be applied to robust intensity representations, such as the normalized cross-correlation (NCC) over local image patches [88].

I would like to ask some clarifications about this point:
- From my understanding, the message here is that it should be possible to replace the dense feature maps (`F_i` in the paper) with some other (potentially not deep NN-based) representations. However, shouldn't this impact the formulation of the KA and BA  problems, depending on the choice of the representation?
- Do you have any pointers or suggestions about the best roadmap to follow, in order to replace the CNN dense feature extraction with some other non NN-based representations?

Thanks a lot for your help!

**Comment by Phil26AT** [comment]
Hi, 

thank you :)

- The current formulation works under the assumption that smaller distance between descriptors results in better geometry, and works with point-wise descriptors (=1x1 patches). If your representation does not fulfill this assumption, you need a different formulation. All kind of dense feature maps used in this repo (S2D-Net, DSIFT, ...) fulfill these assumptions.
- This heavily depends on what you are looking for. If you just want to build better handcrafted dense feature maps, DSIFT is a good reference. If you can find dense descriptors with less dimensions, that would be a really nice improvement too. Another direction would be reformulating KA and BA to optimize high-level geometric constraints. For example, if you have access to some kind of semantics like certain points belong to the same plane, you could reformulate BA/KA to force these points to be on a plane in 3D.

**Comment by lucaBartolomei** [comment]
Hi! Thanks a lot for the detailed answer! The assumptions are overall clearer.
