### ISSUE TITLE
how to run cambridge dataset with pixel-perfect-sfm?

### ISSUE THREAD

**Issue by lululovecode** [cvg/pixel-perfect-sfm#85]
how to run cambridge dataset with pixel-perfect-sfm? and how to make the ply file in eth3d dataset?

**Comment by Phil26AT** [comment]
[hloc](https://github.com/cvg/Hierarchical-Localization/tree/master/hloc/pipelines/Cambridge) offers a pipeline to benchmark on the Cambridge dataset. It should be straightforward to replace calls to triangulation and localization with [our triangulation](https://github.com/cvg/Hierarchical-Localization/tree/master/hloc/pipelines/Cambridge) and [our localization](https://github.com/cvg/pixel-perfect-sfm/blob/main/pixsfm/localize.py#L18).

On ETH3D, the gt PLY files are provided by the dataset (dowload with `python -m pixsfm.eval.eth3d.download`). When evaluating triangulation, every run converts a sparse colmap reconstruction to PLY, and compares the two pointclouds.
