### ISSUE TITLE
Absolute 3D reconstruction

### ISSUE THREAD

**Issue by denred0** [cvg/pixel-perfect-sfm#86]
Thanks for your work! 
I am a new in this sphere and try to understand a lot of things. 
May I use the pixel-perfect-sfm for creating a point cloud with absolute distance to a camera?
I have images, camera poses for every image and camera intrinsic. 

Thank you!

**Comment by Phil26AT** [comment]
Yes in this case you can use our integration with [hloc](https://github.com/cvg/Hierarchical-Localization) to run triangulation: `python -m pixsfm.refine_hloc triangulation -h`. You have to provide a reference SfM model in colmap format. You can easily create this reconstruction (holding images, poses and camera intrinsics) using [pycolmap](https://github.com/colmap/pycolmap). Use hloc to extract and match features, then run triangulation using pixsfm.
