### ISSUE TITLE
How to extract a Mesh?

### ISSUE THREAD

**Issue by amughrabi** [cvg/pixel-perfect-sfm#92]
Thank you for the great work; it is super interesting!

How can I extract colourful meshes?

**Comment by Phil26AT** [comment]
There is a unmerged PR in pycolmap which provides bindings for poisson/delaunay meshing: https://github.com/colmap/pycolmap/pull/93. To improve the mesh quality, I suggest running [MVS](https://github.com/colmap/pycolmap/blob/master/pipeline/mvs.cc) after sparse reconstruction.

**Comment by amughrabi** [comment]
Excellent, it works like a charm!! Thanks a lot for sharing this great information.
