### ISSUE TITLE
Create release for packaging pixel-perfect-sfm in conda-forge

### ISSUE THREAD

**Issue by Tobias-Fischer** [cvg/pixel-perfect-sfm#93]
Hiya, we now have pycolmap and pyceres (soon) on conda-forge. Packaging pixel-perfect-sfm should be straightforward if you create a release that I can pull in.

**Comment by Phil26AT** [comment]
Hi @Tobias-Fischer, thanks for your great work. This would be amazing! We are just preparing some updates on pycolmap and pixsfm, and hope to create a release early next week. 

One question regarding [AVX](https://github.com/cvg/pixel-perfect-sfm/blob/main/pixsfm/base/src/cubic_hermite_spline_simd.h): Do we need to disable this for conda?

**Comment by Tobias-Fischer** [comment]
Awesome that would be great @Phil26AT.

Yes, it is safest to disable avx2 (or ideally check at rubric if it is available). Unfortunately we still don’t have a consistent way to build for multiple instruction sets and install the appropriate one in the conda ecosystem, see https://github.com/conda-forge/conda-forge.github.io/issues/1261

**Comment by Tobias-Fischer** [comment]
Hiya @Phil26AT - quick reminder re a release :)

**Comment by Phil26AT** [comment]
Hiya @Tobias-Fischer , sorry for the long delay. I finally created a release now. AVX2 is enabled by default, but I added a check for it, and disable AVX2 if the test fails.

Thanks a lot for offering your help, it would be great to see pixsfm on conda-forge!

**Comment by Tobias-Fischer** [comment]
This has now been done: https://github.com/conda-forge/pixsfm-feedstock
Installation is easy: `mamba install pixsfm` - works on linux and osx.

I'll soon tweet / advertise this new means of installation :)
