### ISSUE TITLE
I would like to ask which file in hloc should be run to get the input keypoints.h5 in the End-to-end SfM with hloc method?

### ISSUE THREAD

**Issue by newforests** [cvg/pixel-perfect-sfm#94]

**Comment by Phil26AT** [comment]
Hi! You have to run [extract_features.py](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/extract_features.py) to obtain initial keypoints, and [match_features.py](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/match_features.py) to obtain the tentative matches graph.

**Comment by newforests** [comment]
>I get it, thank you very much!!
